# Reward.py

"""Constants for rewards/punishments"""
REWARD_FOR_GRABBING_GOLD = 1000
REWARD_FOR_KILLING_WUMPUS = 50
REWARD_FOR_ESCAPE = 10

PUNISHMENT_FOR_SHOOTING = -100
PUNISHMENT_FOR_DYING = -10000
PUNISHMENT_FOR_MOVING = -10
